=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Gethook
  class AttemptOutcome
    OutcomePending = "pending".freeze
    OutcomeSuccess = "success".freeze
    OutcomeTimeout = "timeout".freeze
    OutcomeNetworkError = "network_error".freeze
    OutcomeHTTP4xx = "http_4xx".freeze
    OutcomeHTTP5xx = "http_5xx".freeze
    OutcomeCancelled = "cancelled".freeze

    def self.all_vars
      @all_vars ||= [OutcomePending, OutcomeSuccess, OutcomeTimeout, OutcomeNetworkError, OutcomeHTTP4xx, OutcomeHTTP5xx, OutcomeCancelled].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AttemptOutcome.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AttemptOutcome"
    end
  end
end
