=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Gethook
  class DeliveryAttempt < ApiModelBase
    attr_accessor :attempt_number

    attr_accessor :destination_id

    attr_accessor :error_message

    attr_accessor :event_id

    attr_accessor :finished_at

    attr_accessor :id

    attr_accessor :latency_ms

    attr_accessor :outcome

    attr_accessor :response_body

    attr_accessor :response_status

    attr_accessor :started_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'attempt_number' => :'attempt_number',
        :'destination_id' => :'destination_id',
        :'error_message' => :'error_message',
        :'event_id' => :'event_id',
        :'finished_at' => :'finished_at',
        :'id' => :'id',
        :'latency_ms' => :'latency_ms',
        :'outcome' => :'outcome',
        :'response_body' => :'response_body',
        :'response_status' => :'response_status',
        :'started_at' => :'started_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'attempt_number' => :'Integer',
        :'destination_id' => :'String',
        :'error_message' => :'String',
        :'event_id' => :'String',
        :'finished_at' => :'String',
        :'id' => :'String',
        :'latency_ms' => :'Integer',
        :'outcome' => :'AttemptOutcome',
        :'response_body' => :'String',
        :'response_status' => :'Integer',
        :'started_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Gethook::DeliveryAttempt` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Gethook::DeliveryAttempt`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'attempt_number')
        self.attempt_number = attributes[:'attempt_number']
      else
        self.attempt_number = nil
      end

      if attributes.key?(:'destination_id')
        self.destination_id = attributes[:'destination_id']
      else
        self.destination_id = nil
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      end

      if attributes.key?(:'event_id')
        self.event_id = attributes[:'event_id']
      else
        self.event_id = nil
      end

      if attributes.key?(:'finished_at')
        self.finished_at = attributes[:'finished_at']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'latency_ms')
        self.latency_ms = attributes[:'latency_ms']
      end

      if attributes.key?(:'outcome')
        self.outcome = attributes[:'outcome']
      else
        self.outcome = nil
      end

      if attributes.key?(:'response_body')
        self.response_body = attributes[:'response_body']
      end

      if attributes.key?(:'response_status')
        self.response_status = attributes[:'response_status']
      end

      if attributes.key?(:'started_at')
        self.started_at = attributes[:'started_at']
      else
        self.started_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @attempt_number.nil?
        invalid_properties.push('invalid value for "attempt_number", attempt_number cannot be nil.')
      end

      if @destination_id.nil?
        invalid_properties.push('invalid value for "destination_id", destination_id cannot be nil.')
      end

      if @event_id.nil?
        invalid_properties.push('invalid value for "event_id", event_id cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @outcome.nil?
        invalid_properties.push('invalid value for "outcome", outcome cannot be nil.')
      end

      if @started_at.nil?
        invalid_properties.push('invalid value for "started_at", started_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @attempt_number.nil?
      return false if @destination_id.nil?
      return false if @event_id.nil?
      return false if @id.nil?
      return false if @outcome.nil?
      return false if @started_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] attempt_number Value to be assigned
    def attempt_number=(attempt_number)
      if attempt_number.nil?
        fail ArgumentError, 'attempt_number cannot be nil'
      end

      @attempt_number = attempt_number
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_id Value to be assigned
    def destination_id=(destination_id)
      if destination_id.nil?
        fail ArgumentError, 'destination_id cannot be nil'
      end

      @destination_id = destination_id
    end

    # Custom attribute writer method with validation
    # @param [Object] event_id Value to be assigned
    def event_id=(event_id)
      if event_id.nil?
        fail ArgumentError, 'event_id cannot be nil'
      end

      @event_id = event_id
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] outcome Value to be assigned
    def outcome=(outcome)
      if outcome.nil?
        fail ArgumentError, 'outcome cannot be nil'
      end

      @outcome = outcome
    end

    # Custom attribute writer method with validation
    # @param [Object] started_at Value to be assigned
    def started_at=(started_at)
      if started_at.nil?
        fail ArgumentError, 'started_at cannot be nil'
      end

      @started_at = started_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          attempt_number == o.attempt_number &&
          destination_id == o.destination_id &&
          error_message == o.error_message &&
          event_id == o.event_id &&
          finished_at == o.finished_at &&
          id == o.id &&
          latency_ms == o.latency_ms &&
          outcome == o.outcome &&
          response_body == o.response_body &&
          response_status == o.response_status &&
          started_at == o.started_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [attempt_number, destination_id, error_message, event_id, finished_at, id, latency_ms, outcome, response_body, response_status, started_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
