=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Gethook
  class DestinationPreset < ApiModelBase
    # for api_key type
    attr_accessor :auth_header

    # e.g. \"Bot Token\", \"API Key\"
    attr_accessor :auth_label

    # \"none\", \"bearer\", \"api_key\"
    attr_accessor :auth_type

    attr_accessor :category

    attr_accessor :color

    attr_accessor :description

    attr_accessor :docs_url

    attr_accessor :extra_headers

    attr_accessor :id

    attr_accessor :name

    attr_accessor :url_hint

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'auth_header' => :'auth_header',
        :'auth_label' => :'auth_label',
        :'auth_type' => :'auth_type',
        :'category' => :'category',
        :'color' => :'color',
        :'description' => :'description',
        :'docs_url' => :'docs_url',
        :'extra_headers' => :'extra_headers',
        :'id' => :'id',
        :'name' => :'name',
        :'url_hint' => :'url_hint'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'auth_header' => :'String',
        :'auth_label' => :'String',
        :'auth_type' => :'String',
        :'category' => :'String',
        :'color' => :'String',
        :'description' => :'String',
        :'docs_url' => :'String',
        :'extra_headers' => :'Hash<String, String>',
        :'id' => :'String',
        :'name' => :'String',
        :'url_hint' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Gethook::DestinationPreset` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Gethook::DestinationPreset`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'auth_header')
        self.auth_header = attributes[:'auth_header']
      end

      if attributes.key?(:'auth_label')
        self.auth_label = attributes[:'auth_label']
      end

      if attributes.key?(:'auth_type')
        self.auth_type = attributes[:'auth_type']
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'color')
        self.color = attributes[:'color']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'docs_url')
        self.docs_url = attributes[:'docs_url']
      end

      if attributes.key?(:'extra_headers')
        if (value = attributes[:'extra_headers']).is_a?(Hash)
          self.extra_headers = value
        end
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'url_hint')
        self.url_hint = attributes[:'url_hint']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          auth_header == o.auth_header &&
          auth_label == o.auth_label &&
          auth_type == o.auth_type &&
          category == o.category &&
          color == o.color &&
          description == o.description &&
          docs_url == o.docs_url &&
          extra_headers == o.extra_headers &&
          id == o.id &&
          name == o.name &&
          url_hint == o.url_hint
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [auth_header, auth_label, auth_type, category, color, description, docs_url, extra_headers, id, name, url_hint].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
