=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Gethook
  class EventStatus
    StatusReceived = "received".freeze
    StatusAccepted = "accepted".freeze
    StatusQueued = "queued".freeze
    StatusDelivering = "delivering".freeze
    StatusDelivered = "delivered".freeze
    StatusRetryScheduled = "retry_scheduled".freeze
    StatusDeadLetter = "dead_letter".freeze
    StatusReplayed = "replayed".freeze

    def self.all_vars
      @all_vars ||= [StatusReceived, StatusAccepted, StatusQueued, StatusDelivering, StatusDelivered, StatusRetryScheduled, StatusDeadLetter, StatusReplayed].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EventStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EventStatus"
    end
  end
end
