=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Gethook
  class Event < ApiModelBase
    attr_accessor :account_id

    attr_accessor :attempts_count

    attr_accessor :body

    attr_accessor :created_at

    attr_accessor :created_by

    attr_accessor :direction

    attr_accessor :event_type

    attr_accessor :external_event_id

    attr_accessor :final_state

    attr_accessor :headers

    attr_accessor :id

    attr_accessor :next_attempt_at

    attr_accessor :payload_hash

    attr_accessor :received_at

    attr_accessor :source_id

    attr_accessor :status

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'account_id',
        :'attempts_count' => :'attempts_count',
        :'body' => :'body',
        :'created_at' => :'created_at',
        :'created_by' => :'created_by',
        :'direction' => :'direction',
        :'event_type' => :'event_type',
        :'external_event_id' => :'external_event_id',
        :'final_state' => :'final_state',
        :'headers' => :'headers',
        :'id' => :'id',
        :'next_attempt_at' => :'next_attempt_at',
        :'payload_hash' => :'payload_hash',
        :'received_at' => :'received_at',
        :'source_id' => :'source_id',
        :'status' => :'status'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'String',
        :'attempts_count' => :'Integer',
        :'body' => :'String',
        :'created_at' => :'String',
        :'created_by' => :'String',
        :'direction' => :'Direction',
        :'event_type' => :'String',
        :'external_event_id' => :'String',
        :'final_state' => :'String',
        :'headers' => :'Hash<String, Object>',
        :'id' => :'String',
        :'next_attempt_at' => :'String',
        :'payload_hash' => :'String',
        :'received_at' => :'String',
        :'source_id' => :'String',
        :'status' => :'EventStatus'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Gethook::Event` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Gethook::Event`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      else
        self.account_id = nil
      end

      if attributes.key?(:'attempts_count')
        self.attempts_count = attributes[:'attempts_count']
      else
        self.attempts_count = nil
      end

      if attributes.key?(:'body')
        self.body = attributes[:'body']
      else
        self.body = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'direction')
        self.direction = attributes[:'direction']
      else
        self.direction = nil
      end

      if attributes.key?(:'event_type')
        self.event_type = attributes[:'event_type']
      end

      if attributes.key?(:'external_event_id')
        self.external_event_id = attributes[:'external_event_id']
      end

      if attributes.key?(:'final_state')
        self.final_state = attributes[:'final_state']
      end

      if attributes.key?(:'headers')
        if (value = attributes[:'headers']).is_a?(Hash)
          self.headers = value
        end
      else
        self.headers = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'next_attempt_at')
        self.next_attempt_at = attributes[:'next_attempt_at']
      end

      if attributes.key?(:'payload_hash')
        self.payload_hash = attributes[:'payload_hash']
      end

      if attributes.key?(:'received_at')
        self.received_at = attributes[:'received_at']
      else
        self.received_at = nil
      end

      if attributes.key?(:'source_id')
        self.source_id = attributes[:'source_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @attempts_count.nil?
        invalid_properties.push('invalid value for "attempts_count", attempts_count cannot be nil.')
      end

      if @body.nil?
        invalid_properties.push('invalid value for "body", body cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @direction.nil?
        invalid_properties.push('invalid value for "direction", direction cannot be nil.')
      end

      if @headers.nil?
        invalid_properties.push('invalid value for "headers", headers cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @received_at.nil?
        invalid_properties.push('invalid value for "received_at", received_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @account_id.nil?
      return false if @attempts_count.nil?
      return false if @body.nil?
      return false if @created_at.nil?
      return false if @direction.nil?
      return false if @headers.nil?
      return false if @id.nil?
      return false if @received_at.nil?
      return false if @status.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] account_id Value to be assigned
    def account_id=(account_id)
      if account_id.nil?
        fail ArgumentError, 'account_id cannot be nil'
      end

      @account_id = account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] attempts_count Value to be assigned
    def attempts_count=(attempts_count)
      if attempts_count.nil?
        fail ArgumentError, 'attempts_count cannot be nil'
      end

      @attempts_count = attempts_count
    end

    # Custom attribute writer method with validation
    # @param [Object] body Value to be assigned
    def body=(body)
      if body.nil?
        fail ArgumentError, 'body cannot be nil'
      end

      @body = body
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] direction Value to be assigned
    def direction=(direction)
      if direction.nil?
        fail ArgumentError, 'direction cannot be nil'
      end

      @direction = direction
    end

    # Custom attribute writer method with validation
    # @param [Object] headers Value to be assigned
    def headers=(headers)
      if headers.nil?
        fail ArgumentError, 'headers cannot be nil'
      end

      @headers = headers
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] received_at Value to be assigned
    def received_at=(received_at)
      if received_at.nil?
        fail ArgumentError, 'received_at cannot be nil'
      end

      @received_at = received_at
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          attempts_count == o.attempts_count &&
          body == o.body &&
          created_at == o.created_at &&
          created_by == o.created_by &&
          direction == o.direction &&
          event_type == o.event_type &&
          external_event_id == o.external_event_id &&
          final_state == o.final_state &&
          headers == o.headers &&
          id == o.id &&
          next_attempt_at == o.next_attempt_at &&
          payload_hash == o.payload_hash &&
          received_at == o.received_at &&
          source_id == o.source_id &&
          status == o.status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, attempts_count, body, created_at, created_by, direction, event_type, external_event_id, final_state, headers, id, next_attempt_at, payload_hash, received_at, source_id, status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
