=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Gethook
  class StatsData < ApiModelBase
    attr_accessor :by_status

    attr_accessor :daily

    attr_accessor :totals

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'by_status' => :'by_status',
        :'daily' => :'daily',
        :'totals' => :'totals'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'by_status' => :'Array<StatsStatusItem>',
        :'daily' => :'Array<StatsDailyItem>',
        :'totals' => :'AggregateTotals'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Gethook::StatsData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Gethook::StatsData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'by_status')
        if (value = attributes[:'by_status']).is_a?(Array)
          self.by_status = value
        end
      else
        self.by_status = nil
      end

      if attributes.key?(:'daily')
        if (value = attributes[:'daily']).is_a?(Array)
          self.daily = value
        end
      else
        self.daily = nil
      end

      if attributes.key?(:'totals')
        self.totals = attributes[:'totals']
      else
        self.totals = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @by_status.nil?
        invalid_properties.push('invalid value for "by_status", by_status cannot be nil.')
      end

      if @daily.nil?
        invalid_properties.push('invalid value for "daily", daily cannot be nil.')
      end

      if @totals.nil?
        invalid_properties.push('invalid value for "totals", totals cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @by_status.nil?
      return false if @daily.nil?
      return false if @totals.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] by_status Value to be assigned
    def by_status=(by_status)
      if by_status.nil?
        fail ArgumentError, 'by_status cannot be nil'
      end

      @by_status = by_status
    end

    # Custom attribute writer method with validation
    # @param [Object] daily Value to be assigned
    def daily=(daily)
      if daily.nil?
        fail ArgumentError, 'daily cannot be nil'
      end

      @daily = daily
    end

    # Custom attribute writer method with validation
    # @param [Object] totals Value to be assigned
    def totals=(totals)
      if totals.nil?
        fail ArgumentError, 'totals cannot be nil'
      end

      @totals = totals
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          by_status == o.by_status &&
          daily == o.daily &&
          totals == o.totals
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [by_status, daily, totals].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
