=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Gethook
  class StatsDailyItem < ApiModelBase
    attr_accessor :date

    attr_accessor :delivered

    attr_accessor :failed

    attr_accessor :inbound

    attr_accessor :outbound

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date' => :'date',
        :'delivered' => :'delivered',
        :'failed' => :'failed',
        :'inbound' => :'inbound',
        :'outbound' => :'outbound'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date' => :'String',
        :'delivered' => :'Integer',
        :'failed' => :'Integer',
        :'inbound' => :'Integer',
        :'outbound' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Gethook::StatsDailyItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Gethook::StatsDailyItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      else
        self.date = nil
      end

      if attributes.key?(:'delivered')
        self.delivered = attributes[:'delivered']
      else
        self.delivered = nil
      end

      if attributes.key?(:'failed')
        self.failed = attributes[:'failed']
      else
        self.failed = nil
      end

      if attributes.key?(:'inbound')
        self.inbound = attributes[:'inbound']
      else
        self.inbound = nil
      end

      if attributes.key?(:'outbound')
        self.outbound = attributes[:'outbound']
      else
        self.outbound = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @date.nil?
        invalid_properties.push('invalid value for "date", date cannot be nil.')
      end

      if @delivered.nil?
        invalid_properties.push('invalid value for "delivered", delivered cannot be nil.')
      end

      if @failed.nil?
        invalid_properties.push('invalid value for "failed", failed cannot be nil.')
      end

      if @inbound.nil?
        invalid_properties.push('invalid value for "inbound", inbound cannot be nil.')
      end

      if @outbound.nil?
        invalid_properties.push('invalid value for "outbound", outbound cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @date.nil?
      return false if @delivered.nil?
      return false if @failed.nil?
      return false if @inbound.nil?
      return false if @outbound.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] date Value to be assigned
    def date=(date)
      if date.nil?
        fail ArgumentError, 'date cannot be nil'
      end

      @date = date
    end

    # Custom attribute writer method with validation
    # @param [Object] delivered Value to be assigned
    def delivered=(delivered)
      if delivered.nil?
        fail ArgumentError, 'delivered cannot be nil'
      end

      @delivered = delivered
    end

    # Custom attribute writer method with validation
    # @param [Object] failed Value to be assigned
    def failed=(failed)
      if failed.nil?
        fail ArgumentError, 'failed cannot be nil'
      end

      @failed = failed
    end

    # Custom attribute writer method with validation
    # @param [Object] inbound Value to be assigned
    def inbound=(inbound)
      if inbound.nil?
        fail ArgumentError, 'inbound cannot be nil'
      end

      @inbound = inbound
    end

    # Custom attribute writer method with validation
    # @param [Object] outbound Value to be assigned
    def outbound=(outbound)
      if outbound.nil?
        fail ArgumentError, 'outbound cannot be nil'
      end

      @outbound = outbound
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date == o.date &&
          delivered == o.delivered &&
          failed == o.failed &&
          inbound == o.inbound &&
          outbound == o.outbound
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date, delivered, failed, inbound, outbound].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
