=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::ApiKeysApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApiKeysApi' do
  before do
    # run before each test
    @api_instance = Gethook::ApiKeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiKeysApi' do
    it 'should create an instance of ApiKeysApi' do
      expect(@api_instance).to be_instance_of(Gethook::ApiKeysApi)
    end
  end

  # unit tests for create_api_key
  # Create API key
  # Creates a new API key for the authenticated account. The full key is only returned once.
  # @param create_api_key_request Key name
  # @param [Hash] opts the optional parameters
  # @return [APIKeyWithSecret]
  describe 'create_api_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_api_key
  # Revoke API key
  # @param id API key UUID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_api_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_api_keys
  # List API keys
  # @param [Hash] opts the optional parameters
  # @return [Array<APIKey>]
  describe 'list_api_keys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
