=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::AuthApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthApi' do
  before do
    # run before each test
    @api_instance = Gethook::AuthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthApi' do
    it 'should create an instance of AuthApi' do
      expect(@api_instance).to be_instance_of(Gethook::AuthApi)
    end
  end

  # unit tests for login
  # Login with email and password
  # Authenticates with email/password and returns a fresh API key on success.
  # @param login_request Login credentials
  # @param [Hash] opts the optional parameters
  # @return [AccountBootstrapData]
  describe 'login test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for register
  # Register with email and password
  # Creates a new account with email/password credentials and returns a bootstrap API key.
  # @param register_request Registration details
  # @param [Hash] opts the optional parameters
  # @return [AccountBootstrapData]
  describe 'register test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
