=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::BrandApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BrandApi' do
  before do
    # run before each test
    @api_instance = Gethook::BrandApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BrandApi' do
    it 'should create an instance of BrandApi' do
      expect(@api_instance).to be_instance_of(Gethook::BrandApi)
    end
  end

  # unit tests for get_brand_settings
  # Get brand settings
  # @param [Hash] opts the optional parameters
  # @return [BrandSettings]
  describe 'get_brand_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upsert_brand_settings
  # Upsert brand settings
  # Creates or replaces white-label brand settings for the account.
  # @param upsert_brand_settings_request Brand settings
  # @param [Hash] opts the optional parameters
  # @return [BrandSettings]
  describe 'upsert_brand_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
