=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::CustomDomainsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomDomainsApi' do
  before do
    # run before each test
    @api_instance = Gethook::CustomDomainsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomDomainsApi' do
    it 'should create an instance of CustomDomainsApi' do
      expect(@api_instance).to be_instance_of(Gethook::CustomDomainsApi)
    end
  end

  # unit tests for create_custom_domain
  # Create custom domain
  # @param create_custom_domain_request Domain details
  # @param [Hash] opts the optional parameters
  # @return [CustomDomain]
  describe 'create_custom_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_custom_domains
  # List custom domains
  # @param [Hash] opts the optional parameters
  # @return [Array<CustomDomain>]
  describe 'list_custom_domains test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
