=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::DestinationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DestinationsApi' do
  before do
    # run before each test
    @api_instance = Gethook::DestinationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DestinationsApi' do
    it 'should create an instance of DestinationsApi' do
      expect(@api_instance).to be_instance_of(Gethook::DestinationsApi)
    end
  end

  # unit tests for create_destination
  # Create destination
  # Creates a new webhook delivery destination. The signing_secret is encrypted at rest and never returned.
  # @param create_destination_request Destination config
  # @param [Hash] opts the optional parameters
  # @return [Destination]
  describe 'create_destination test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_destination
  # Get destination
  # @param id Destination UUID
  # @param [Hash] opts the optional parameters
  # @return [Destination]
  describe 'get_destination test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_destinations
  # List destinations
  # @param [Hash] opts the optional parameters
  # @return [Array<Destination>]
  describe 'list_destinations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_destination
  # Update destination
  # @param id Destination UUID
  # @param update_destination_request Fields to update
  # @param [Hash] opts the optional parameters
  # @return [Destination]
  describe 'update_destination test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
