=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::EventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EventsApi' do
  before do
    # run before each test
    @api_instance = Gethook::EventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsApi' do
    it 'should create an instance of EventsApi' do
      expect(@api_instance).to be_instance_of(Gethook::EventsApi)
    end
  end

  # unit tests for get_event
  # Get inbound event
  # @param id Event UUID
  # @param [Hash] opts the optional parameters
  # @return [EventDetailData]
  describe 'get_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_events
  # List inbound events
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max results (default 25, max 200)
  # @option opts [Integer] :offset Pagination offset
  # @return [EventListData]
  describe 'list_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for replay_event
  # Replay inbound event
  # Creates a new queued copy of the event for re-delivery.
  # @param id Event UUID
  # @param [Hash] opts the optional parameters
  # @return [ReplayEventData]
  describe 'replay_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
