=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::IngestApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IngestApi' do
  before do
    # run before each test
    @api_instance = Gethook::IngestApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IngestApi' do
    it 'should create an instance of IngestApi' do
      expect(@api_instance).to be_instance_of(Gethook::IngestApi)
    end
  end

  # unit tests for ingest
  # Ingest webhook event
  # Accepts an inbound webhook. The path token authenticates the source — no Bearer header required.
  # @param token Source path token (src_...)
  # @param [Hash] opts the optional parameters
  # @return [IngestAcceptedData]
  describe 'ingest test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
