=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::OutboundEventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OutboundEventsApi' do
  before do
    # run before each test
    @api_instance = Gethook::OutboundEventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OutboundEventsApi' do
    it 'should create an instance of OutboundEventsApi' do
      expect(@api_instance).to be_instance_of(Gethook::OutboundEventsApi)
    end
  end

  # unit tests for get_outbound_event
  # Get outbound event
  # @param id Event UUID
  # @param [Hash] opts the optional parameters
  # @return [EventDetailData]
  describe 'get_outbound_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_outbound_events
  # List outbound events
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max results (default 25, max 200)
  # @option opts [Integer] :offset Pagination offset
  # @return [EventListData]
  describe 'list_outbound_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for publish_outbound_event
  # Publish outbound event
  # Queues a new outbound event for delivery to all matching route destinations.
  # @param publish_outbound_event_request Event payload
  # @param [Hash] opts the optional parameters
  # @return [PublishOutboundData]
  describe 'publish_outbound_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for replay_outbound_event
  # Replay outbound event
  # @param id Event UUID
  # @param [Hash] opts the optional parameters
  # @return [ReplayEventData]
  describe 'replay_outbound_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
