=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::RoutesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RoutesApi' do
  before do
    # run before each test
    @api_instance = Gethook::RoutesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RoutesApi' do
    it 'should create an instance of RoutesApi' do
      expect(@api_instance).to be_instance_of(Gethook::RoutesApi)
    end
  end

  # unit tests for create_route
  # Create route
  # Creates a routing rule that forwards matching events from a source to a destination.
  # @param create_route_request Route config
  # @param [Hash] opts the optional parameters
  # @return [Route]
  describe 'create_route test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_routes
  # List routes
  # @param [Hash] opts the optional parameters
  # @return [Array<Route>]
  describe 'list_routes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
