=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Gethook::SourcesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SourcesApi' do
  before do
    # run before each test
    @api_instance = Gethook::SourcesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SourcesApi' do
    it 'should create an instance of SourcesApi' do
      expect(@api_instance).to be_instance_of(Gethook::SourcesApi)
    end
  end

  # unit tests for create_source
  # Create source
  # Creates a new webhook source endpoint. Returns an ingest_url to share with the event sender.
  # @param create_source_request Source config
  # @param [Hash] opts the optional parameters
  # @return [Source]
  describe 'create_source test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_source
  # Get source
  # @param id Source UUID
  # @param [Hash] opts the optional parameters
  # @return [Source]
  describe 'get_source test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_sources
  # List sources
  # @param [Hash] opts the optional parameters
  # @return [Array<Source>]
  describe 'list_sources test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
