=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Gethook::AttemptOutcome
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Gethook::AttemptOutcome do
  #let(:instance) { Gethook::AttemptOutcome.new }

  describe 'test an instance of AttemptOutcome' do
    it 'should create an instance of AttemptOutcome' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Gethook::AttemptOutcome)
    end
  end

end
