=begin
#GetHook API

#Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

# Common files
require 'gethook/api_client'
require 'gethook/api_error'
require 'gethook/api_model_base'
require 'gethook/version'
require 'gethook/configuration'

# Models
require 'gethook/models/api_key'
require 'gethook/models/api_key_with_secret'
require 'gethook/models/account'
require 'gethook/models/account_bootstrap_data'
require 'gethook/models/aggregate_totals'
require 'gethook/models/attempt_outcome'
require 'gethook/models/brand_settings'
require 'gethook/models/create_api_key_request'
require 'gethook/models/create_account_request'
require 'gethook/models/create_custom_domain_request'
require 'gethook/models/create_destination_request'
require 'gethook/models/create_route_request'
require 'gethook/models/create_source_request'
require 'gethook/models/custom_domain'
require 'gethook/models/delivery_attempt'
require 'gethook/models/destination'
require 'gethook/models/destination_preset'
require 'gethook/models/direction'
require 'gethook/models/error_response'
require 'gethook/models/event'
require 'gethook/models/event_detail_data'
require 'gethook/models/event_list_data'
require 'gethook/models/event_status'
require 'gethook/models/ingest_accepted_data'
require 'gethook/models/login_request'
require 'gethook/models/platform_stats'
require 'gethook/models/provider_preset'
require 'gethook/models/publish_outbound_data'
require 'gethook/models/publish_outbound_event_request'
require 'gethook/models/register_request'
require 'gethook/models/replay_event_data'
require 'gethook/models/retry_policy'
require 'gethook/models/route'
require 'gethook/models/source'
require 'gethook/models/stats_daily_item'
require 'gethook/models/stats_data'
require 'gethook/models/stats_status_item'
require 'gethook/models/update_destination_request'
require 'gethook/models/upsert_brand_settings_request'

# APIs
require 'gethook/api/brand_api'
require 'gethook/api/custom_domains_api'
require 'gethook/api/destinations_api'
require 'gethook/api/events_api'
require 'gethook/api/health_api'
require 'gethook/api/ingest_api'
require 'gethook/api/outbound_events_api'
require 'gethook/api/platform_api'
require 'gethook/api/routes_api'
require 'gethook/api/sources_api'
require 'gethook/api/stats_api'

module Gethook
  class << self
    # Customize default settings for the SDK using block.
    #   Gethook.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
